Co co 476 Build Test
bcgov/digital.gov.bc.ca pull request #506
Opened 2021-01-08 01:15 UTC by thegentlemanphysicist

2021-01-11 06:26 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +This is used by the frontend to navigate to the coco when clicking on the card.  The uid should be automatically generated based on the CoCo Name entered
coco should be "CoCo"

2021-01-11 06:27 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +Name of the team that created the CoCo
missing period

2021-01-11 06:28 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +The name of the common component.
I'd be consistent throughout this doc with either "CoCo" or "common component".

2021-01-11 06:28 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +-- red: Abandonned
spelling: Abandoned

2021-01-11 06:30 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +Select the best estimate for the time needed to implement a given coco.  (hours days, weeks, months)
missing period at end

2021-01-11 06:30 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +A logo or image that represents the CoCo
missing period at end

2021-01-11 06:30 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +This is a tag associated with the ministries using the CoCo
missing period

2021-01-11 06:31 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +Three of these components are needed on each CoCo to advertise it's best features. It has three fields:
"its" instead of "it's"

2021-01-11 06:32 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +Directs interested parties to other technical docs.  Two fields
missing colon after "Two fields"

2021-01-11 06:32 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +- Heading: Eye catching headline of a few words.
remove period at end

2021-01-11 06:32 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +- Heading: Eye catching headline of a few words.
remove period at end

2021-01-11 06:33 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +Directs interested parties to other any additional documentation about requirements and restrictions.  Two fields
missing colon after "Two fields"

2021-01-11 06:33 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +- Header: Text describing the documentation.
remove periods here

2021-01-11 06:35 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +- Header: a description of the contact (e.g. Support managed through githup issues)
Change "githup" to "GitHub"

2021-01-11 06:35 UTC, mark-a-wilson commented on docs/StrapiContentManager/CoCoReadMe.md
> +- PhoneURLorEmail: a phone number, website, or e-email contact.
remove extra "e-"

2021-01-11 06:48 UTC, mark-a-wilson requested changes
I was unable to create a new CoCo: 
* Content cannot be saved until **all** required values are entered.
* Two of those required values are the **CoverImage** and **WhyShouldIUseThis** sections, each of which require images to be selected. 
* In both places, I attempted to upload images from my Desktop (max file size was 172 KB), but received an error message: “An internal server error occurred”.

2021-01-14 20:11 UTC, mark-a-wilson approved these changes
Submitting an Approve review here in case it's needed to cancel out my previous Request Changes review. Thanks for tidying up the README punctuation 🙂

Have not re-tested creating the CoCo in Strapi myself — relying on @singhinderdeep's review to confirm that.

2021-01-19 18:17 UTC, parulmishra approved these changes

2021-01-19 18:23 UTC, merged