Adjust layout of DigitalBC Livestream feature
bcgov/digital.gov.bc.ca pull request #970
Opened 2021-10-07 16:31 UTC by mark-a-wilson

This PR addresses:

1. Feedback from Ari to make the layout of the feature more intuitive (see #969)
2. The clickable area on links in a few places (see #959)

2022-01-26 21:16 UTC, SteveChapmanBCDX commented
Mark to update to current dev branch and request review from Brad.

2022-01-27 21:00 UTC, bdolor requested changes
Recommend making an effort, where feasible, to move away from inline styling and towards using classNames for sanity and better maintainability. 

https://reactjs.org/docs/faq-styling.html

2022-02-04 19:35 UTC, mark-a-wilson commented
@SteveChapmanBCDX and @bdolor :

Totally understand Brad's concern with the inline styles in `bcLivesteam.js` (which I followed suit in this PR).  

I started revising this PR to remove all of the inline styles but have realized it would take me a lot of time to componentize everything. Not sure it's worth the effort based on how much user value this styling change would deliver.

The PR as is achieves the desired styling improvements, but I'll leave it up to you guys if you want to merge as is with the mess or simply close it, unmerged. No hard feelings if the latter.

2022-02-09 20:00 UTC, bdolor approved these changes

2022-03-08 22:44 UTC, merged